version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client/StichHub"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "server"
    schedule:
      interval: "monthly"
