name: "✨ Feature Request Form"
description: "Suggest an idea for this project"
title: "Feat:"
labels: ["Feat", "Needs Triage"]
body:
  - type: checkboxes
    attributes:
      label: "Is there an existing issue raised for this?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - label: "I have searched the existing issues"
          required: true

  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "Describe the feature you are requesting."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Add Screenshots"
      description: "Add sufficient screenshots to explain your issue."
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: "Record Options"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I'm a GSSOC'23 contributor"
        - label: "I want to work on this issue"
