/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 human.glb
Author: aaron.kalvin (https://sketchfab.com/aaron.kalvin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-03a70758739544b3aa705c13af3872b1
Title: Human
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("../3D-Model/human.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Realistic_White_Male_Low_Poly_Default_OBJ001_0.geometry}
        material={materials["Default_OBJ.001"]}
        position={[22.05, 0, 164.64]}
        rotation={[-Math.PI / 2, 0, 2.98]}
        scale={59.09}
      />
    </group>
  );
}

// useGLTF.preload('/human.glb')
