import React, { useState } from "react";
import {
  ContactUsVector,
  EmailIcon,
  AvatarIcon,
  PhoneIcon,
  SendVector,
} from "../../assets/MainLandingPage/Icons";

const initialForm = {
  name: "",
  email: "",
  phoneno: "",
  message: "",
};

const ContactUs = () => {
  const [form, setForm] = useState(initialForm);
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    //send the form data to email using formsubmit.co
    const { name, email, phoneno, message } = form;

    //replace the email with the random string generated by formsubmit.co sent to your mail after creating the form
    const res = await fetch("https://formsubmit.co/ajax/uba.gcoen@gmail.com", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name,
        email,
        phoneno,
        message,
      }),
    });

    //check if the email is sent successfully
    if (res.ok) {
      setIsLoading(false);
      alert("Your message has been sent successfully");
    }

    //reset the form
    setForm(initialForm);
  };

  return (
    <div
      id="contactus"
      className="h-[100%] relative mt-10 lg:mt-0 p-10 lg:p-20 lg:ml-20 lg:mr-20"
    >
      <div className="relative z-[5] flex justify-evenly">
        {/* left-Side */}
        <div id="leftside" className="lg:block hidden mb-[20px] bottom-[20p]">
          <img src={ContactUsVector} className="" />
          <p className="text-left text-xl w-[500px]"></p>
        </div>

        {/* Right-Side */}
        <div id="rightSide" className="">
          {/* Title */}
          <div id="Headings" className="text-left">
            <h1 id="title" className="lg:text-5xl font-medium pb-4">
              GET IN TOUCH
            </h1>
            <span id="subTitle" className="text-lg lg:text-3xl text-slate-300">
              We will answer your every questions and problems
            </span>
          </div>

          {/* Form */}
          <form id="form-Container" className="" method="POST" onSubmit={handleSubmit}>
            <div id="yourName" className="">
              <img
                src={AvatarIcon}
                alt="N"
                id="icon"
                className="absolute ml-[10px] mt-[12px] h-9"
              />
              <input
                pattern="[A-Za-z ]+"  // Only alphabets and spaces are allowed
                required
                autoComplete="on"
                type="text"
                placeholder="Your Name"
                name="name"
                id="name"
                value={form.name}
                onChange={handleChange}
                className="mt-[30px] block w-full py-[16px] pl-[80px] bg-white border border-slate-300 rounded-2xl text-xl shadow-sm placeholder-slate-400 text-black focus:font-medium
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
                disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
                invalid:border-pink-500 invalid:text-pink-600
                focus:invalid:border-pink-500 focus:invalid:ring-pink-500"
              ></input>
            </div>
            <div id="Email" className="">
              <img
                src={EmailIcon}
                alt="E"
                id="icon"
                className="absolute ml-[10px] mt-[12px] h-9"
              />
              <input
                required
                pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"  // Email pattern
                autoComplete="on"
                type="email"
                placeholder="Email"
                name="email"
                id="email"
                value={form.email}
                onChange={handleChange}
                className="mt-[30px] block w-full py-[16px] pl-[80px] bg-white border border-slate-300 rounded-2xl text-xl shadow-sm placeholder-slate-400 text-black focus:font-medium
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
                disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
                invalid:border-pink-500 invalid:text-pink-600
                focus:invalid:border-pink-500 focus:invalid:ring-pink-500"
              ></input>
            </div>
            <div id="Phone no." className="">
              <img
                src={PhoneIcon}
                alt="P"
                id="icon"
                className="absolute ml-[10px] mt-[12px] h-9"
              />
              <input
                required
                pattern="[0-9]{10}"  // Only 10 digits are allowed
                type="tel"
                placeholder="Phone no."
                name="phoneno"
                id="phoneno"
                value={form.phoneno}
                onChange={handleChange}
                className="mt-[30px] block w-full py-[16px] pl-[80px] bg-white border border-slate-300 rounded-2xl text-xl shadow-sm placeholder-slate-400 text-black focus:font-medium
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
                disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
                invalid:border-pink-500 invalid:text-pink-600
                focus:invalid:border-pink-500 focus:invalid:ring-pink-500"
              ></input>
            </div>
            <textarea
              required
              placeholder="Describe your issue here"
              name="message"
              id="message"
              cols="30"
              rows="6"
              value={form.message}
              onChange={handleChange}
              className="mt-[30px] block w-full py-[16px] pl-[40px] bg-white border border-slate-300 rounded-2xl text-xl shadow-sm placeholder-slate-400 text-black focus:font-medium
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
                disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
                invalid:border-pink-500 invalid:text-pink-600
                focus:invalid:border-pink-500 focus:invalid:ring-pink-500
                resize-none"
            ></textarea>
            <button
              id="submit"
              type="submit"
              className="mt-[30px] block w-full bg-[#0054B8] py-3 lg:py-[16px] rounded-2xl hover:bg-violet-600 active:bg-violet-700 focus:outline-none focus:ring focus:ring-violet-300 lg:text-3xl text-lg"
            >
              {isLoading ? (
                <div className="flex justify-center items-center">
                  <svg
                    className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24">
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12z"></path>
                  </svg>
                  <span className="text-white">Loading...</span>
                </div>
              ) : (
                <span className="text-white">Submit</span>
              )
              }
            </button>
          </form>
          <img
            src={SendVector}
            alt="send"
            className="hidden lg:block absolute right-[-120px] bottom-[1px]"
          />
        </div>
      </div>

      {/* BG-Gradients */}
      <div className="absolute circleGradient-blue w-[670px] h-[570px] bottom-[-40px] left-[-200px] z-0 blur-xl"></div>
      <div className="absolute circleGradient-peach w-[370px] h-[370px] top-[40px] left-[700px] z-0 blur-xl"></div>
    </div>
  );
};

export default ContactUs;
