name: Linting
on:
  pull_request_target:
     types:
       - opened 
jobs:

  Linting:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Lint code with prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
          token: ${{ secrets.GH_TOKEN }}

