name: Reviewpad

on:
  issues:
  issue_comment:
  pull_request_target:

# These permissions are necessary to automate pull requests from forks.
permissions:
  pull-requests: write
  issues: write

jobs:
  reviewpad_job:
    runs-on: ubuntu-latest
    name: Reviewpad
    # Don't run reviewpad on automated PRs
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          file: .github/config/reviewpad.yml
